CREATE TABLE firstTable (
id INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
gool VARCHAR(20),
wol VARCHAR(20),
hul VARCHAR(20)
);

INSERT INTO firstTable(gool, wol, hul) VALUES('lol', 'kul', 'jul');
INSERT INTO firstTable(gool, wol, hul) VALUES('lol', 'kul', 'jul');

CREATE TABLE name (
id INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
name VARCHAR(20)
);