CREATE TABLE tag (
tag_id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
tag_name VARCHAR(20),
CONSTRAINT tag_pk PRIMARY KEY (tag_id)
);

CREATE TABLE name (
name_id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
name_name VARCHAR(20),
CONSTRAINT name_pk PRIMARY KEY (name_id)
);

CREATE TABLE content (
content_id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
tag_id INTEGER,
name_id INTEGER,
CONSTRAINT content_pk PRIMARY KEY (content_id),
CONSTRAINT content_fk1 FOREIGN KEY (tag_id) REFERENCES tag(tag_id),
CONSTRAINT content_fk2 FOREIGN KEY (name_id) REFERENCES name(name_id)
);